#!/usr/bin/env bash
# Bash completion for {{CLI_NAME}}
# Generated by BOB Core

_{{CLI_NAME}}_completion() {
    local cur prev words cword
    _init_completion || return

    # Set environment variables for completion engine
    export COMP_LINE="${COMP_LINE}"
    export COMP_POINT="${COMP_POINT}"
    export COMP_CWORD="${COMP_CWORD}"
    export COMP_WORDS="${COMP_WORDS[*]}"

    # Call CLI to get suggestions
    local suggestions
    suggestions=$({{CLI_PATH}} completion suggest 2>/dev/null)

    # Return suggestions as completions
    COMPREPLY=($(compgen -W "${suggestions}" -- "${cur}"))
}

# Register completion function
complete -F _{{CLI_NAME}}_completion {{CLI_NAME}}
