# Fish completion for {{CLI_NAME}}
# Generated by BOB Core

function __{{CLI_NAME}}_complete
    # Get current command line and cursor position
    set -l line (commandline -cp)
    set -l point (commandline -C)

    # Call CLI to get suggestions
    {{CLI_PATH}} completion suggest --line="$line" --point="$point" 2>/dev/null
end

# Register completions
complete -c {{CLI_NAME}} -f -a '(__{{CLI_NAME}}_complete)'
