#compdef {{CLI_NAME}}
# Zsh completion for {{CLI_NAME}}
# Generated by BOB Core

_{{CLI_NAME}}_completion() {
    local -a suggestions
    local line point cword

    # Set environment variables for completion engine
    export COMP_LINE="${BUFFER}"
    export COMP_POINT="${CURSOR}"
    export COMP_CWORD="$((CURRENT - 1))"
    export COMP_WORDS="${words[*]}"

    # Call CLI to get suggestions
    suggestions=(${(f)"$({{CLI_PATH}} completion suggest 2>/dev/null)"})

    # Return suggestions
    _describe '{{CLI_NAME}} commands' suggestions
}

# Register completion function
compdef _{{CLI_NAME}}_completion {{CLI_NAME}}
