import { COMPLETE_COMMAND, CompletionCandidate } from '@/src/completion/types.js';

export type FishScriptOptions = {
	/** The executable name as typed, e.g. `bdg` — not the human-facing CLI name. */
	binName: string;
};

/** fish function names allow far less than a binary name does. */
function functionName(binName: string): string {
	return `__${binName.replace(/[^a-zA-Z0-9_]/g, '_')}_complete`;
}

/**
 * The script installed at `~/.config/fish/completions/<bin>.fish`.
 *
 * It holds no command names of its own — it asks the binary on every keypress — so it never goes
 * stale when commands or flags change, and never needs regenerating.
 *
 * `-f` suppresses filename completion: our candidate list is the whole answer, and mixing files
 * into the command list is noise. The cost is that path-typed arguments don't complete filenames.
 */
export function renderFishScript(opts: FishScriptOptions): string {
	const { binName } = opts;
	const fn = functionName(binName);

	return [
		`# Completions for ${binName}, generated by \`${binName} completion fish\`.`,
		'# Regenerating is only needed if this file is deleted — candidates are resolved at runtime.',
		'',
		`function ${fn}`,
		'\t# Via a variable, for two reasons. fish does not expand command substitution inside double',
		'\t# quotes, so an inline `"--current=(commandline -ct)"` would be passed through literally.',
		'\t# And the quoted expansion keeps an empty token as one argument, which is what distinguishes',
		'\t# "cmd <TAB>" from "cmd<TAB>" — an unquoted empty substitution contributes zero arguments.',
		'\tset -l token (commandline -ct)',
		`\t${binName} ${COMPLETE_COMMAND} fish "--current=$token" -- (commandline -opc) 2>/dev/null`,
		'end',
		'',
		`complete -c ${binName} -f -a "(${fn})"`,
		'',
	].join('\n');
}

/**
 * fish reads one candidate per line, `value<TAB>description`.
 *
 * Tabs and newlines are stripped from descriptions rather than escaped — a description carrying
 * either would split into a bogus extra candidate.
 */
export function encodeFishCandidates(candidates: CompletionCandidate[]): string {
	return candidates
		.map(candidate => {
			const description = sanitize(candidate.description);
			return description ? `${candidate.value}\t${description}` : candidate.value;
		})
		.join('\n');
}

// Descriptions are written for the help screen, so a fair number arrive chalk-styled. Matching an
// escape sequence is the whole job here, hence the exemption.
// eslint-disable-next-line no-control-regex
const ANSI = new RegExp('\\u001B\\[[0-9;]*m', 'g');

function sanitize(description?: string): string {
	if (!description) return '';

	return description
		.replace(ANSI, '')
		.replace(/[\t\r\n]+/g, ' ')
		.trim();
}
